### ISSUE TITLE
数据和Xcode和自带的工具有些差距

### ISSUE THREAD

**Issue by kekeYezi** [JustKeepRunning/LXDAppMonitor#2]
发现测出来的数据和Xcode 自带的工具有些不同 是什么原因呢？

**Comment by sindrilin** [comment]
是的，比如内存这项数据，instructments的内存检测采用的是malloc_logger指针的机制实现的，监控malloc和vmalloc相关的内存分配进行计算的，所以和现有的采集方案都不一样

**Comment by kekeYezi** [comment]
非常感谢解答，有没有哪种方案更准确这么一说呢？
